export const MAX_ZOOM = 8;
export const PEN_DEFAULT_SIZE = 6;
export const HIGHLIGHT_DEFAULT_SIZE = 20;
export const PEN_HIGHLIGHT_DEFAULT_COLOR = '#000000';
export const DRAW_MIN_SIZE = 1;
export const DRAW_MAX_SIZE = 20;

export const ARROW_DEFAULT_SIZE = 2;
export const ARROW_MAX_SIZE = 20;
export const ARROW_MIN_SIZE = 1;

export const DEFAULT_FONT_SIZE = 14;
export const FONT_SIZES = [10, 12, 14, 18, 24, 36, 48, 64, 80, 144, 288];

export const CUSTOM_RECTANGLE_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_RECTANGLE_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_RECTANGLE_SOFT_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_RECTANGLE_SOFT_SHAPE_DEFAULT_HEIGHT = 100;

export const MIND_MAP_CHILD_INPUT_DEFAULT_WIDTH = 144;
export const MIND_MAP_CHILD_INPUT_DEFAULT_HEIGHT = 44;

export const MIND_MAP_MAIN_INPUT_DEFAULT_WIDTH = 208;
export const MIND_MAP_MAIN_INPUT_DEFAULT_HEIGHT = 76;

export const CUSTOM_ELLIPSE_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_ELLIPSE_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_POLYGON_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_POLYGON_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_RHOMBUS_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_RHOMBUS_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_BUBBLE_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_BUBBLE_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_PARALLELOGRAM_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_PARALLELOGRAM_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_STAR_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_STAR_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_ARROW_RIGHT_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_ARROW_RIGHT_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_SOFT_ARROW_SHAPE_DEFAULT_WIDTH = 200;
export const CUSTOM_SOFT_ARROW_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_SEXAGON_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_SEXAGON_SHAPE_DEFAULT_HEIGHT = 100;

export const CUSTOM_TEXT_SHAPE_DEFAULT_WIDTH = 200;
export const CUSTOM_TEXT_SHAPE_DEFAULT_HEIGHT = 18;

export const CUSTOM_NOTE_SHAPE_DEFAULT_WIDTH = 100;
export const CUSTOM_NOTE_SHAPE_DEFAULT_HEIGHT = 100;
