export const CUSTOM_RECTANGLE_SHAPE_ID = 'custom-rectangle' as const;
export const CUSTOM_RECTANGLE_SOFT_SHAPE_ID = 'custom-rectangle-soft' as const;
export const CUSTOM_ELLIPSE_SHAPE_ID = 'custom-ellipse' as const;
export const CUSTOM_POLYGON_SHAPE_ID = 'custom-polygon' as const;
export const CUSTOM_RHOMBUS_SHAPE_ID = 'custom-rhombus' as const;
export const CUSTOM_BUBBLE_SHAPE_ID = 'custom-bubble' as const;
export const CUSTOM_PARALLELOGRAM_SHAPE_ID = 'custom-parallelogram' as const;
export const CUSTOM_STAR_SHAPE_ID = 'custom-star' as const;
export const CUSTOM_ARROW_RIGHT_SHAPE_ID = 'custom-arrow-right' as const;
export const CUSTOM_SEXAGON_SHAPE_ID = 'custom-sexagon' as const;
export const CUSTOM_TEXT_SHAPE_ID = 'custom-text' as const;
export const CUSTOM_NOTE_SHAPE_ID = 'custom-note' as const;
export const CUSTOM_HIGHLIGHT_SHAPE_ID = 'custom-highlight' as const;
export const CUSTOM_DRAW_SHAPE_ID = 'custom-draw' as const;
export const CUSTOM_SQUARE_ARROW_SHAPE_ID = 'custom-square-arrow' as const;
export const CUSTOM_STRAIGHT_ARROW_SHAPE_ID = 'custom-straight-arrow' as const;
export const CUSTOM_LINE_SHAPE_ID = 'custom-line' as const;
export const CUSTOM_SOFT_ARROW_SHAPE_ID = 'custom-soft-arrow' as const;
export const MIND_MAP_CHILD_INPUT_SHAPE_ID = 'mind-map-child-input' as const;
export const MIND_MAP_MAIN_INPUT_SHAPE_ID = 'mind-map-main-input' as const;
export const MIND_MAP_SOFT_ARROW_SHAPE_ID = 'mind-map-soft-arrow' as const;
export const MIND_MAP_SQUARE_ARROW_SHAPE_ID = 'mind-map-square-arrow' as const;
export const EMOJI_SHAPE_ID = 'emoji' as const;

export type CUSTOM_RECTANGLE_SHAPE_ID_TYPE = typeof CUSTOM_RECTANGLE_SHAPE_ID;
export type CUSTOM_RECTANGLE_SOFT_SHAPE_ID_TYPE = typeof CUSTOM_RECTANGLE_SOFT_SHAPE_ID;
export type CUSTOM_ELLIPSE_SHAPE_ID_TYPE = typeof CUSTOM_ELLIPSE_SHAPE_ID;
export type CUSTOM_POLYGON_SHAPE_ID_TYPE = typeof CUSTOM_POLYGON_SHAPE_ID;
export type CUSTOM_RHOMBUS_SHAPE_ID_TYPE = typeof CUSTOM_RHOMBUS_SHAPE_ID;
export type CUSTOM_BUBBLE_SHAPE_ID_TYPE = typeof CUSTOM_BUBBLE_SHAPE_ID;
export type CUSTOM_PARALLELOGRAM_SHAPE_ID_TYPE = typeof CUSTOM_PARALLELOGRAM_SHAPE_ID;
export type CUSTOM_STAR_SHAPE_ID_TYPE = typeof CUSTOM_STAR_SHAPE_ID;
export type CUSTOM_ARROW_RIGHT_SHAPE_ID_TYPE = typeof CUSTOM_ARROW_RIGHT_SHAPE_ID;
export type CUSTOM_SEXAGON_SHAPE_ID_TYPE = typeof CUSTOM_SEXAGON_SHAPE_ID;
export type CUSTOM_TEXT_SHAPE_ID_TYPE = typeof CUSTOM_TEXT_SHAPE_ID;
export type CUSTOM_NOTE_SHAPE_ID_TYPE = typeof CUSTOM_NOTE_SHAPE_ID;
export type CUSTOM_HIGHLIGHT_SHAPE_ID_TYPE = typeof CUSTOM_HIGHLIGHT_SHAPE_ID;
export type CUSTOM_DRAW_SHAPE_ID_TYPE = typeof CUSTOM_DRAW_SHAPE_ID;
export type CUSTOM_SQUARE_ARROW_SHAPE_ID_TYPE = typeof CUSTOM_SQUARE_ARROW_SHAPE_ID;
export type CUSTOM_STRAIGHT_ARROW_SHAPE_ID_TYPE = typeof CUSTOM_STRAIGHT_ARROW_SHAPE_ID;
export type CUSTOM_LINE_SHAPE_ID_TYPE = typeof CUSTOM_LINE_SHAPE_ID;
export type CUSTOM_SOFT_ARROW_SHAPE_ID_TYPE = typeof CUSTOM_SOFT_ARROW_SHAPE_ID;
export type MIND_MAP_CHILD_INPUT_SHAPE_ID_TYPE = typeof MIND_MAP_CHILD_INPUT_SHAPE_ID;
export type MIND_MAP_MAIN_INPUT_SHAPE_ID_TYPE = typeof MIND_MAP_MAIN_INPUT_SHAPE_ID;
export type MIND_MAP_SOFT_ARROW_SHAPE_ID_TYPE = typeof MIND_MAP_SOFT_ARROW_SHAPE_ID;
export type MIND_MAP_SQUARE_ARROW_SHAPE_ID_TYPE = typeof MIND_MAP_SQUARE_ARROW_SHAPE_ID;
export type EMOJI_SHAPE_ID_TYPE = typeof EMOJI_SHAPE_ID;

export const CUSTOM_SHAPE_IDS = [
  CUSTOM_RECTANGLE_SHAPE_ID,
  CUSTOM_RECTANGLE_SOFT_SHAPE_ID,
  CUSTOM_ELLIPSE_SHAPE_ID,
  CUSTOM_POLYGON_SHAPE_ID,
  CUSTOM_RHOMBUS_SHAPE_ID,
  CUSTOM_BUBBLE_SHAPE_ID,
  CUSTOM_PARALLELOGRAM_SHAPE_ID,
  CUSTOM_STAR_SHAPE_ID,
  CUSTOM_ARROW_RIGHT_SHAPE_ID,
  CUSTOM_SEXAGON_SHAPE_ID,
  CUSTOM_TEXT_SHAPE_ID,
  CUSTOM_NOTE_SHAPE_ID,
  CUSTOM_HIGHLIGHT_SHAPE_ID,
  CUSTOM_DRAW_SHAPE_ID,
  MIND_MAP_CHILD_INPUT_SHAPE_ID,
  MIND_MAP_MAIN_INPUT_SHAPE_ID,
  EMOJI_SHAPE_ID,
];

export type CUSTOM_SHAPE_ID_TYPES =
  | CUSTOM_RECTANGLE_SHAPE_ID_TYPE
  | CUSTOM_RECTANGLE_SOFT_SHAPE_ID_TYPE
  | CUSTOM_ELLIPSE_SHAPE_ID_TYPE
  | CUSTOM_POLYGON_SHAPE_ID_TYPE
  | CUSTOM_RHOMBUS_SHAPE_ID_TYPE
  | CUSTOM_BUBBLE_SHAPE_ID_TYPE
  | CUSTOM_PARALLELOGRAM_SHAPE_ID_TYPE
  | CUSTOM_STAR_SHAPE_ID_TYPE
  | CUSTOM_ARROW_RIGHT_SHAPE_ID_TYPE
  | CUSTOM_SEXAGON_SHAPE_ID_TYPE
  | CUSTOM_TEXT_SHAPE_ID_TYPE
  | CUSTOM_NOTE_SHAPE_ID_TYPE
  | CUSTOM_HIGHLIGHT_SHAPE_ID_TYPE
  | CUSTOM_DRAW_SHAPE_ID_TYPE
  | MIND_MAP_MAIN_INPUT_SHAPE_ID_TYPE
  | MIND_MAP_CHILD_INPUT_SHAPE_ID_TYPE
  |EMOJI_SHAPE_ID_TYPE;