import {
  MICROSOFT_OFFICE_DOCUMENT_MIME_TYPES,
  TEXT_DOCUMENT_MIME_TYPES,
} from '@shared/lib/constants/mime-types';

export const FILE_TYPES_TO_EXTENSIONS_MAP = {
  [TEXT_DOCUMENT_MIME_TYPES.PDF]: 'pdf',
  [TEXT_DOCUMENT_MIME_TYPES.TEXT_PLAIN]: 'doc',
  [TEXT_DOCUMENT_MIME_TYPES.CSV]: 'doc',
  [MICROSOFT_OFFICE_DOCUMENT_MIME_TYPES.DOC]: 'doc',
  [MICROSOFT_OFFICE_DOCUMENT_MIME_TYPES.DOCX]: 'doc',
  [MICROSOFT_OFFICE_DOCUMENT_MIME_TYPES.XLS]: 'doc',
  [MICROSOFT_OFFICE_DOCUMENT_MIME_TYPES.XLSX]: 'doc',
} as const;
